{{- $fullName := include "flux-web.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  labels:
{{ include "flux-web.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- if .Values.ingress.redirect.enabled }}
    - http:
        paths:
        - backend:
            serviceName: redirect
            servicePort: use-annotation
          path: {{ .Values.ingress.redirect.path }}
  {{- end -}}
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range $k, $v := .paths }}
        {{- range $service, $path := $v }}
          - path: {{ $path }}
            backend:
              serviceName: "{{ $fullName }}-{{ $service }}"
              servicePort: http
        {{- end }}
        {{- end }}
  {{- end }}